#!/usr/bin/env bash
# Install nginx on my webserver

sudo apt-get update -y
sudo apt-get install -y nginx

echo 'Hello World!' | sudo  tee /var/www/html/index.html >/dev/null

sudo service nginx restart
