#!/usr/bin/env bash
# Configure a new web server


# Update package
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html >/dev/null

sudo tee /etc/nginx/sites-available/default >/dev/null <<EOF
server {
	listen 80;
	listen [::]:80;
	add_header X-Served-By $HOSTNAME;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location = /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}
EOF


sudo service nginx restart
