#!/usr/bin/env bash
# Back's up all the data

DATE=$(date +"%d-%m-%y")
DUMP_FILE="backup.sql"

if [ "$#" -ne 1 ]; then
	echo "Usage $0 <root_password>"
	exit 1
fi

# Create the sql dump
mysqldump -u root -p "$1" --all-databases --single-transaction > "$DUMP_FILE"

# Compress to tar.gz
tar -czf "$DATE.tar.gz" "$DUMP_FILE"
