#!/usr/bin/env bash
# Parses Apache log files in list format.
#	Groups visitors by IP and HTTP Status code.
#	Displays the number of occurrences
#	code for each log, in a sorted order


awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
