#!/usr/bin/env bash
# Loops from one to 10
# Prints "bad luck" on 4th iter
# Prints "good luck" on 8th iter
# Prints "Best School otherwise"

count=1

while [ $count -le 10 ]; do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi

	((count++))
done
