#!/usr/bin/env bash
# Display the time for 12 hours 59 minutes
# Example:
#			Hour: 1
#				1
#				2
#				...
#				59
#			Hour: 2
#			...
#			Hour: 12
#				...
#				59


hour=0

while [ $hour -le 12 ]; do
	echo "Hour: $hour"

	min=1

	while [ $min -le 59 ]; do
		echo $min
		((min++))
	done

	((hour++))
done
