#!/usr/bin/env bash
# Configure Nginx as user

sed -i 's/user\s*\(.*\);/user nginx;/' /etc/nginx/nginx.conf

sed -i 's/listen\s*\(.*\);/listen 8080;/' /etc/nginx/conf.d/default.conf

service nginx restart
